[data]
    name = {{ prompt "Your name" "John Doe" }}
    email = {{ prompt "Your email" "john.doe@example.com" }}
    # You can customize these based on your preferences
    editor = "vi"  # Default editor, change to vim, nvim, etc. as needed

    git = true
    node = true
    ssh = true
    fzf = true
    tmux = true
    termutils = true

[diff]
    pager = "delta"

[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]