{{- $termutils := promptBoolOnce . "termutils" "Enable termutils (true/false)" false -}}
{{- $git_email := promptStringOnce . "git_email" "Email address" -}}
{{- $git_name := promptStringOnce . "git_name" "git user name" -}}

[data]
    name = {{ $git_name | quote }}
    email = {{ $git_email | quote }}
    editor = "vi"
    git = true
    node = true
    ssh = true
    fzf = true
    tmux = true
    termutils = {{ $termutils }}

[diff]
    pager = "delta"

[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]